#!/usr/bin/env python3

import os, json, re, random

from ..utilities import BasePlugin

JSON_LINES_FILE = os.path.join(os.path.dirname(os.path.realpath(__file__)), "haiku_lines.json") # haiku candidate lines, generated by `src/plugins/haiku/generate_haiku_lines.py`

class HaikuPlugin(BasePlugin):
    """
    Haiku generator plugin for Botty.

    Here, haikus are defined as three sentences with five, seven, and five syllables, respectively.

    The `mhyph.txt` file is the [MOBY Hyphenation List](http://www.gutenberg.org/ebooks/3204), taken from the MOBY English language project.

    Example invocations:

        #general    | Me: pls haiku me
        #general    | Botty: ```
        but for good reason
        something something teleport
        that thing with that guy
        ```
        #general    | Me: haiku me pls
        #general    | Botty: ```
        that's pretty good news
        but you can control that stuff
        "accidentally"
        ```
    """
    def __init__(self, bot):
        super().__init__(bot)

        try:
            with open(JSON_LINES_FILE) as f:
                result = json.load(f)
                self.five_syllable_messages = result["five_syllables"] or ["refrigerator"]
                self.seven_syllable_messages = result["seven_syllables"] or ["seven refrigerators"]
        except FileNotFoundError:
            self.logger.warning("can't find haiku lines JSON file `{}` - try running `python3 src/plugins/haiku/generate_haiku_lines.py`".format(JSON_LINES_FILE))
            self.five_syllable_messages = []
            self.seven_syllable_messages = []

    def on_message(self, m):
        if not m.is_user_text_message: return False
        if not re.search(r"\b(?:pls\s+haiku\s+me|haiku\s+me\s+pls)\b", m.text, re.IGNORECASE): return False

        # fail gracefully if user has not configured this plugin yet
        if not self.five_syllable_messages or not self.seven_syllable_messages:
            self.respond_raw("```\nthis poem is shown\nwhen there are no haiku lines\nrefrigerator\n```\n(try running `python3 src/plugins/haiku/generate_haiku_lines.py` to generate the haiku lines)")
            return True

        # generate haiku
        self.respond_raw("```\n{}\n{}\n{}\n```".format(
            random.choice(self.five_syllable_messages),
            random.choice(self.seven_syllable_messages),
            random.choice(self.five_syllable_messages)
        ))
        return True
